# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('D', 'Deshabilitado')], default='A', max_length=1),
        ),
    ]
