# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slink',
            name='estado',
            field=models.CharField(choices=[('A', 'habilitado'), ('D', 'deshabilitado')], default='A', max_length=1),
        ),
    ]
