# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 10:18
from __future__ import unicode_literals

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160518_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='slug',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='slink',
            name='url',
            field=models.URLField(unique=True,),
        ),
    ]
