# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160130_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('D', 'Deshabilitado')], default='A', max_length=1),
        ),
    ]
