# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160606_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='slug',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
