# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 15:42
from __future__ import unicode_literals

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160622_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slink',
            name='slug',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.MaxLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='slink',
            name='url',
            field=models.URLField(unique=True, validators=[app.models.clean_url]),
        ),
    ]
